server:
  port: 12345
  context-path: /demo

com.wt.title: wtrover
com.wt.description: 分享生活和技术

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_test1?useUnicode=true&amp;charaterEncoding=utf-8
    username: root
    password: terry
  jpa:
    show-sql: true
    properties.hibernate.hbm2ddl.auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: smtp.163.com
    username: youremail@163.com
    password: yourpwd
    default-encoding: UTF-8
    #超时时间，可选
    properties:
      mail:
        smtp:
          connectiontimeout: 5000  
          timeout: 3000
          writetimeout: 5000