server:
  port: 12345
  context-path: /demo

com.wt.title: wtrover
com.wt.description: ^_^

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_test1?useUnicode=true&amp;charaterEncoding=utf-8
    username: root
    password: terry
  jpa:
    show-sql: true
    properties.hibernate.hbm2ddl.auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    # 数据库索引（默认为0）
    database: 0
    # 服务器地址
    host: localhost
    # 服务器连接端口
    port: 6379
    # 服务器连接密码（默认为空）
    password: 
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
    # 连接池中的最大空闲连接
    max-idle: 8
    # 连接池中的最小空闲连接
    min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 10000