server:
  port: 12345
  context-path: /demo

com.wt.title: wtrover
com.wt.description: ^_^

spring:
  datasource:
    # Druid
    druid:
      # 初始化大小、最小、最大连接数
      initial-size: 3
      min-idle: 3
      max-active: 10
      # 配置获取连接等待超时时间
      max-wait: 60000
      # 监控后台账号和密码
      stat-view-servlet.login-username: admin
      stat-view-servlet.login-password: admin
      # 配置StatFilter
      filter.stat.log-slow-sql: true
      filter.stat.slow-sql-millis: 2000
      # 数据源1
      one:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/spring_boot_test3?useUnicode=true&amp;charaterEncoding=utf-8
        username: root
        password: terry
        # Druid 数据源 1 配置，继承 spring.datasource.druid.* 配置，相同则覆盖
        max-active: 20
        max-wait: 10000
      # 数据源2
      two:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/spring_boot_test4?useUnicode=true&amp;charaterEncoding=utf-8
        username: root
        password: terry
        # Druid 数据源 2 配置，继承spring.datasource.druid.* 配置，相同则覆盖
        max-active: 30
        max-wait: 20000

mybatis:
  type-aliases-package: com.wuti.demo.entity
  mapper-locations:
    one: classpath:mybatis/mapper/one/*.xml
    two: classpath:mybatis/mapper/two/*.xml
  
logging.level.com.wuti.demo.mapper: debug